export const URL='http://localhost:3000';
export const USER_LIST_API_REQUEST = "USER_LIST_API_REQUEST";
export const USER_LIST_API_SUCCESS = "USER_LIST_API_SUCCESS";
export const USER_LIST_API_FAILURE = "USER_LIST_API_FAILURE";
export const USER_DETAIL_VIEW = "USER_DETAIL_VIEW";